/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardResultRouteImport } from './routes/dashboard.result'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardUploadRouteImport } from './routes/dashboard.upload'
import { Route as DashboardAnalysisIdRouteImport } from './routes/dashboard.analysis.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResultRoute = DashboardResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalysisIdRoute = DashboardAnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/result': typeof DashboardResultRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/analysis/$id': typeof DashboardAnalysisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/result': typeof DashboardResultRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/analysis/$id': typeof DashboardAnalysisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/result': typeof DashboardResultRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/analysis/$id': typeof DashboardAnalysisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/result'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/'
    | '/dashboard/analysis/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/result'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard'
    | '/dashboard/analysis/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/result'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/'
    | '/dashboard/analysis/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/result': {
      id: '/dashboard/result'
      path: '/result'
      fullPath: '/dashboard/result'
      preLoaderRoute: typeof DashboardResultRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analysis/$id': {
      id: '/dashboard/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/dashboard/analysis/$id'
      preLoaderRoute: typeof DashboardAnalysisIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardResultRoute: typeof DashboardResultRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAnalysisIdRoute: typeof DashboardAnalysisIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardResultRoute: DashboardResultRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAnalysisIdRoute: DashboardAnalysisIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
